### PR TITLE
HOP-2296 Fix HopVfsFileDialog optimal column width

### PR DESCRIPTION
**Pull request by nadment**
Replace the TreeUtil.setOptimalWidthOnColumns method with a simpler solution to solve the 2 issues

Need to be carefully tested on Linux / Max before merging

### CODE REVIEW

**Comment by usbrandon** [comment]
Opening the file dialog worked and the column widths looked good.  However, I got an NPE when double clicking on a folder.  
Windows 10.  -- In the current master build of hop before your Pull Request, There is a SWT exception and it also fails.

It gave the following stack trace:
Error browsing to location: C:\Users\usbra\Box
NullPointerException: 
Root cause: NullPointerException: 

java.lang.NullPointerException
	at org.eclipse.swt.widgets.TreeItem.getBounds(TreeItem.java:419)
	at org.eclipse.swt.widgets.TreeColumn.pack(TreeColumn.java:371)
	at org.apache.hop.ui.core.widget.TreeUtil.setOptimalWidthOnColumns(TreeUtil.java:29)
	at org.apache.hop.ui.core.vfs.HopVfsFileDialog.resizeTableColumn(HopVfsFileDialog.java:1211)
	at org.apache.hop.ui.core.vfs.HopVfsFileDialog.lambda$open$7(HopVfsFileDialog.java:465)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4105)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1042)
	at org.eclipse.swt.widgets.Tree.windowProc(Tree.java:5768)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4749)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(Native Method)
	at org.eclipse.swt.widgets.Tree.callWindowProc(Tree.java:1454)
	at org.eclipse.swt.widgets.Tree.windowProc(Tree.java:5830)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4749)
	at org.eclipse.swt.internal.win32.OS.SetScrollInfo(Native Method)
	at org.eclipse.swt.widgets.Tree.updateScrollBar(Tree.java:5650)
	at org.eclipse.swt.widgets.Tree.callWindowProc(Tree.java:1601)
	at org.eclipse.swt.widgets.Scrollable.WM_SIZE(Scrollable.java:348)
	at org.eclipse.swt.widgets.Composite.WM_SIZE(Composite.java:1714)
	at org.eclipse.swt.widgets.Tree.WM_SIZE(Tree.java:7071)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4795)
	at org.eclipse.swt.widgets.Tree.windowProc(Tree.java:5929)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4749)
	at org.eclipse.swt.internal.win32.OS.CallWindowProc(Native Method)
	at org.eclipse.swt.widgets.Tree.callWindowProc(Tree.java:1546)
	at org.eclipse.swt.widgets.Control.WM_WINDOWPOSCHANGED(Control.java:5644)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4808)
	at org.eclipse.swt.widgets.Tree.windowProc(Tree.java:5929)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4749)
	at org.eclipse.swt.internal.win32.OS.CallWindowProc(Native Method)
	at org.eclipse.swt.widgets.Tree.callWindowProc(Tree.java:1546)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4819)
	at org.eclipse.swt.widgets.Tree.windowProc(Tree.java:5929)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4757)
	at org.eclipse.swt.internal.win32.OS.SendMessage(Native Method)
	at org.eclipse.swt.widgets.Tree.removeAll(Tree.java:3933)
	at org.apache.hop.ui.core.vfs.HopVfsFileDialog.refreshBrowser(HopVfsFileDialog.java:761)
	at org.apache.hop.ui.core.vfs.HopVfsFileDialog.navigateTo(HopVfsFileDialog.java:1068)
	at org.apache.hop.ui.core.vfs.HopVfsFileDialog.fileDefaultSelected(HopVfsFileDialog.java:692)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4105)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3922)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3524)
	at org.apache.hop.ui.core.vfs.HopVfsFileDialog.open(HopVfsFileDialog.java:520)
	at org.apache.hop.ui.core.dialog.BaseDialog.presentFileDialog(BaseDialog.java:192)
	at org.apache.hop.ui.core.dialog.BaseDialog.presentFileDialog(BaseDialog.java:97)
	at org.apache.hop.ui.hopgui.delegates.HopGuiFileDelegate.fileOpen(HopGuiFileDelegate.java:66)
	at org.apache.hop.ui.hopgui.HopGui.menuFileOpen(HopGui.java:530)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hop.ui.core.gui.BaseGuiWidgets.lambda$getListener$1(BaseGuiWidgets.java:145)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4105)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3922)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3524)
	at org.apache.hop.ui.hopgui.HopGui.open(HopGui.java:363)
	at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:299)

image

**Comment by nadment** [comment]
@usbrandon can you try with this version (calculate column width in UI thread) ?

**Comment by usbrandon** [comment]
Your latest push fixed the NPE issue and I can browse into folders.  There are some strange things that happen though, for example the window opens with a weird default size (too narrow), but the folder name's are perfect.  The column headers flicker into the dialog at the top.   --- So it functions, but now a flicker and some additional resizing are required.


2020-12-13_11-36-11- Flickering Column Names

**Comment by usbrandon** [comment]
I tried something else on my computer, a Lenovo P53 with both Intel 630 and Nvidia capabilities.  In the BIOS it was set to "Hybrid". When I changed this to discrete, which causes only the Nvidia card to be used, the flicker went away.  Hybrid mode must be trying to use the Intel chip for some graphic rendering and Nvidia for other.  Somewhere in there I guess there is a conflict that can cause this flickering. -- So I would still give this fix a thumbs up.

**Comment by nadment** [comment]
Here is a new version which deactivates the refreshing during the calculation of the 3 columns

**Comment by usbrandon** [comment]
I got further, but something else fails about the file selection.  For example when I used an Excel Input step (no project, no environment), and just browsed to an Excel file in my home directory, once I clicked OK, then there is a SWT Widget disposed problem.

image

The following stack trace was present:
java.lang.RuntimeException: Error executing method : editTransform in class org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph
	at org.apache.hop.core.gui.plugin.action.GuiActionLambdaBuilder.lambda$createLambda$0(GuiActionLambdaBuilder.java:98)
	at org.apache.hop.ui.hopgui.context.GuiContextUtil.handleActionSelection(GuiContextUtil.java:143)
	at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.showActionDialog(HopGuiPipelineGraph.java:1171)
	at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.lambda$mouseUp$1(HopGuiPipelineGraph.java:1039)
	at org.eclipse.swt.widgets.Display.runTimer(Display.java:4020)
	at org.eclipse.swt.widgets.Display.messageProc(Display.java:3146)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3522)
	at org.apache.hop.ui.hopgui.HopGui.open(HopGui.java:363)
	at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:299)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hop.core.gui.plugin.action.GuiActionLambdaBuilder.lambda$createLambda$0(GuiActionLambdaBuilder.java:93)
	... 9 more
Caused by: org.eclipse.swt.SWTException: Failed to execute runnable (org.eclipse.swt.SWTException: Widget is disposed)
	at org.eclipse.swt.SWT.error(SWT.java:4723)
	at org.eclipse.swt.SWT.error(SWT.java:4638)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:188)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3897)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3527)
	at org.apache.hop.ui.core.dialog.ErrorDialog.showErrorDialog(ErrorDialog.java:217)
	at org.apache.hop.ui.core.dialog.ErrorDialog.<init>(ErrorDialog.java:95)
	at org.apache.hop.ui.core.dialog.ErrorDialog.<init>(ErrorDialog.java:82)
	at org.apache.hop.ui.hopgui.file.pipeline.delegates.HopGuiPipelineTransformDelegate.editTransform(HopGuiPipelineTransformDelegate.java:226)
	at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.editTransform(HopGuiPipelineGraph.java:3176)
	at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.editTransform(HopGuiPipelineGraph.java:2145)
	... 14 more
Caused by: org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4723)
	at org.eclipse.swt.SWT.error(SWT.java:4638)
	at org.eclipse.swt.SWT.error(SWT.java:4609)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:432)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:351)
	at org.eclipse.swt.widgets.Tree.setRedraw(Tree.java:4748)
	at org.apache.hop.ui.core.widget.TreeUtil.lambda$setOptimalWidthOnColumns$0(TreeUtil.java:30)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	... 22 more

Another small glitch is while browsing to the folder, I happened to have a really long file in one of the directories.  The horizontal scroll bar at the bottom would not allow any kind of movement and it seemed like the UI froze for a moment.   After the UI became responsive again, I was able to browse for the Excel file I was looking for, and upon selecting it, the above stack trace came out.

image

**Comment by hansva** [comment]
@usbrandon , confirmed it is now working as expected

**Pull request merged**
