### PR TITLE
HOP-2564: Resolve filterPath to resolve ${HOP_CONFIG_FOLDER}

### PR DESCRIPTION
**Pull request by HiromuHota**
Following this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/HOP) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[HOP-XXX] - Fixes bug in SessionManager`,
       where you replace `HOP-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean install apache-rat:check` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [x] If you have a group of commits related to the same change, please squash your commits into one and force push your branch using `git rebase -i`. 
 
Trivial changes like typos do not require a JIRA issue (javadoc, comments...). 
In this case, just format the pull request title like `(DOC) - Add javadoc in SessionManager`.
 
If this is your first contribution, you have to read the [Contribution Guidelines](https://hop.apache.org/community/contributing/)

If your pull request is about ~20 lines of code you don't need to sign an [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) 
if you are unsure please ask on the developers list.

To make clear that you license your contribution under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [ ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by HiromuHota** [comment]
@hansva @mattcasters
First I tried to resolve `homeFolder` at `org.apache.hop.projects.xp.HopGuiFileDefaultFolder.callExtensionPoint(ILogChannel, IVariables, HopGuiFileDialogExtension)`, but the `variables` was null.
Instead the PR currently resolves it at `org.apache.hop.ui.core.vfs.HopVfsFileDialog.setFilterPath(String)`, which works fine, but I'm not sure if this is the right place to resolve it.
Where do you think should it be resolved?

**Comment by hansva** [comment]
I think that is the reasonable place to resolve this, the main issue I have was that the regular hop-ui listens to the 
-DHOP_CONFIG_FOLDER and makes it the root folder to find the configurations.
Once you have an active project it will also honour it's "${PROJECT_HOME}" 

It seems in the web context this is ignored forcing us to add the variable to the paths...
@mattcasters what do you think? do we fix it like this or find the root cause why hop-web doesn't change it's default browsing folder to PROJECT_HOME?

**Comment by mattcasters** [comment]
Yeah I think things are bit more complicated if we want to have multiple users on a server.
So in general I think you could have a user to HOP_CONFIG_FOLDER/HOP_AUDIT_FOLDER/... mapping.
Perhaps it's easy to come up with a simple JSON file.

I tried hop.war earlier today and the config folder maps to `/var/lib/tomcat9/config` on my laptop.  It's all write protected so a bit of a pain.  However, if I had a config file in `/var/lib/tomcat9/conf/hop-web.json` with a simple mapping from the standard "tomcat" user to where I want that user mapped perhaps we can run with it like this.

**Comment by mattcasters** [comment]
If needed we can add some `isWeb()` specific code to HopGui, before `HopEnvironment.init()` which loads a file like `conf/hop-web.json` and sets the relevant system variables.

**Comment by hansva** [comment]
Point taken, we will need to figure out something smart for multiple users!
I'm not against the idea that our vfs browser can resolve variables in the filepath, so this change is still valid!

**Comment by HiromuHota** [comment]
@hansva @mattcasters Thanks for your comments. Let's fix this at `HopVfsFileDialog`.

**Pull request merged**
