### PR TITLE
HOP-2483, HOP-2496 Fix translator and sort i18n messages

### PR DESCRIPTION
**Pull request by nadment**
Tested on Windows, must be tested on other OS!

### CODE REVIEW

**Comment by hansva** [comment]
- When saving translations a timestamp is added, but because of the sort this is added on the wrong location.

- Might be better to remove both those timestamps and the `File generated by Hop Translator for package ...``

- When creating a new translation file the location is incorrect Created abort file in dutch and it saved to following location
`/Users/hans/git/incuba**tor-hoporg/apac**he/hop/pipeline/transforms/abort/messages/messages_nl_NL.properties`

The new message file path is calculated incorrectly

**Comment by hansva** [comment]
@nadment can you check if new translation files are stored in the correct location now?

**Comment by nadment** [comment]
Created message file have incorrect path: 
\plugins\**tranorg**\apache\hop\pipeline\transforms\fake\messages\messages_fr_FR.properties

**Comment by mattcasters** [comment]
I'm looking into it.  The problem stems from the new `i18n:package:key` formats which cause some confusion.
The source folder is calculated incorrectly for those values.

**Comment by mattcasters** [comment]
https://issues.apache.org/jira/browse/HOP-2619

**Comment by hansva** [comment]
@mattcasters , you want these changes merged first?

**Comment by mattcasters** [comment]
> @mattcasters , you want these changes merged first?

Yes I didn't have time yet to merge this into the PR.  Feel free to do so.

**Pull request merged**
