### PR TITLE
HOP-3013 Adapt ContextDialog position to monitor

### PR DESCRIPTION
**Pull request by nadment**
I would test tomorrow with multiple monitors, but if anyone can test on Linux / Max / WebHop

### CODE REVIEW

**Comment by hansva** [comment]
It only works when you are using your primary monitor.
If you work on your secondary monitor it trips (unless the resolutions of those monitors are the same)

**Comment by hansva** [comment]
This still does not really give the desired result on mac, I'll take a look tomorrow if I can gather a bit more information on what is happening. I have a feeling it is still giving the size of the primary display.

**Comment by hansva** [comment]
Works in Hop Web too, if you can confirm Windows it's ready for merge

**Review by hansva — APPROVED** [review]

**Comment by nadment** [comment]
Works fine on Windows, but tested with only one monitor

**Pull request merged**
