### PR TITLE
[Hop-3196] - Added example using javascript transform to convert JDE dates to ISO dates

### PR DESCRIPTION
**Pull request by usbrandon**
Following this checklist to help us incorporate your contribution quickly and easily:

 - [X] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/HOP) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [X] Each commit in the pull request should have a meaningful subject line and body.
 - [X] Format the pull request title like `[HOP-XXX] - Fixes bug in SessionManager`,
       where you replace `HOP-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean install apache-rat:check` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [x] If you have a group of commits related to the same change, please squash your commits into one and force push your branch using `git rebase -i`. 
 
Trivial changes like typos do not require a JIRA issue (javadoc, comments...). 
In this case, just format the pull request title like `(DOC) - Add javadoc in SessionManager`.
 
If this is your first contribution, you have to read the [Contribution Guidelines](https://hop.apache.org/community/contributing/)

If your pull request is about ~20 lines of code you don't need to sign an [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) 
if you are unsure please ask on the developers list.

To make clear that you license your contribution under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by hansva** [comment]
Hi @usbrandon,

You need to add following variable to your project and re-save all the pipelines and workflows you made.
HOP_LICENSE_HEADER_FILE	${PROJECT_HOME}/../asf-header.txt

The header is located in the integration-testing folder. Adding this variable will add the needed header to complete this PR.

**Review by mattcasters — APPROVED** [review]

**Comment by mattcasters** [comment]
Brandon, just add a license header to the .hpl and the check will pass.

**Comment by usbrandon** [comment]
I'll look at how to do that.  I did not really understand about the
HOP_LICENSE_HEADER_FILE thing Hans mentioned.  I developed the HPL from a
snapshot build and just moved a file into the path where I observed samples
getting scooped up from and placed in the destination samples folders.

**Comment by mattcasters** [comment]
Documenting in https://issues.apache.org/jira/browse/HOP-3204

https://github.com/apache/incubator-hop/blob/3dfc300f675a7f5cdfb0f1256123702c5bc33ca7/docs/hop-dev-manual/modules/ROOT/pages/setup-dev-environment.adoc#copyright

**Pull request merged**
