### PR TITLE
[HOP-2943] created unit test for only concatenating some fields in the stream

### PR DESCRIPTION
**Pull request by jballment**
Following this checklist to help us incorporate your contribution quickly and easily:

 - [X ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/HOP) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [X ] Each commit in the pull request should have a meaningful subject line and body.
 - [X ] Format the pull request title like `[HOP-XXX] - Fixes bug in SessionManager`,
       where you replace `HOP-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the commit message.
 - [X ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [not code change but a new unit test that force current code to error ] Run `mvn clean install apache-rat:check` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [X ] If you have a group of commits related to the same change, please squash your commits into one and force push your branch using `git rebase -i`. 
 
Trivial changes like typos do not require a JIRA issue (javadoc, comments...). 
In this case, just format the pull request title like `(DOC) - Add javadoc in SessionManager`.
 
If this is your first contribution, you have to read the [Contribution Guidelines](https://hop.apache.org/community/contributing/)

If your pull request is about ~20 lines of code you don't need to sign an [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) 
if you are unsure please ask on the developers list.

To make clear that you license your contribution under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [X ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
 - [X ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by hansva** [comment]
Hi @jballment Thanks for the contribution!

Can you add the unit test to the existing main-0004-concat-fields.hwf?
there is no need to create a workflow per test.

We have been using the structure 1 workflow per transform and add multiple test there.

Example
Wokflow: main-0006-groupby.hwf 
Unit test pipelines : 0006-groupby-all-rows.hpl, 0006-groupby-basics.hpl, 0006-groupby-no-group.hpl

**Review by hansva — CHANGES_REQUESTED** [review]
see above comment

**Comment by jballment** [comment]
Hi,

I've removed the main-004-concat-some-fields.hwf and added the unit test
into main-004-concat-fields.hwf as requested.

I then squashed the original change with these changes and pushed it to my
forked repo.  I then went to resubmit the pull request but the existing
pull request seems to now have the updated version (I'm not sure if that is
what you were expecting to happen).

Please let me know whether I've submitted this correctly; we don't do "pull
requests" and "squashing" changes in our environments.

Regards,

*John Ballment*
Mobile: 0418 740 871
Email: ***@***.***

Before printing, please consider the environment.

**Comment by jballment** [comment]
Added code fix for issue with concat fields.  This does change it's behavior, all fields are returned + new concatenated field.  This is similar to how PDI outputs looks for the equivalent step.

**Review by hansva — APPROVED** [review]

**Pull request merged**
